# Generated by Django 3.2 on 2021-06-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('th_id', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('minor', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('initials', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(blank=True, max_length=300, null=True)),
                ('year_end', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('th_id', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('path', models.ImageField(blank=True, default='profile/blank_profile.png', null=True, upload_to='profile/')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('th_id', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('rank', models.CharField(blank=True, max_length=100, null=True)),
                ('rank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
