# Generated by Django 3.2 on 2021-06-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.AlterField(
            model_name='education',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='th_id',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
