# Generated by Django 3.2 on 2021-06-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20210609_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='th_id',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
