# Generated by Django 3.2 on 2021-06-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20210609_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
