# Generated by Django 3.2 on 2021-06-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
