# Generated by Django 3.2 on 2021-06-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_documents_doc_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='type_doc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
