# Generated by Django 3.2 on 2021-06-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20210611_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_id', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_id', models.CharField(blank=True, max_length=13, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('classroom', models.IntegerField(blank=True, null=True)),
                ('room', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
