# Generated by Django 3.2 on 2021-06-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
