# Generated by Django 3.2 on 2021-05-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_member_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Majoractivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('responsible', models.CharField(max_length=30)),
                ('money', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Minoractivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('major_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('responsible', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=30)),
                ('money', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ref1', models.CharField(max_length=100)),
                ('ref2', models.CharField(max_length=100)),
                ('ref3', models.CharField(max_length=100)),
                ('introduction', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MinorBenefit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minor_id', models.IntegerField()),
                ('order', models.IntegerField()),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MinorCost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minor_id', models.IntegerField()),
                ('order', models.IntegerField()),
                ('detail', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('money', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='MinorEvaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minor_id', models.IntegerField()),
                ('type_ev', models.CharField(max_length=20)),
                ('order', models.IntegerField()),
                ('detail', models.CharField(max_length=200)),
                ('criteria', models.DecimalField(decimal_places=2, max_digits=5)),
                ('method', models.CharField(blank=True, max_length=200, null=True)),
                ('measure', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinorGoal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minor_id', models.IntegerField()),
                ('type_goal', models.CharField(max_length=20)),
                ('order', models.IntegerField()),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MinorObjective',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minor_id', models.IntegerField()),
                ('order', models.IntegerField()),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MinorOperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minor_id', models.IntegerField()),
                ('type_op', models.CharField(max_length=20)),
                ('order', models.IntegerField()),
                ('date', models.CharField(max_length=20)),
                ('responsible', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
    ]
