# Generated by Django 3.2 on 2021-05-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_majoractivity_minoractivity_minorbenefit_minorcost_minorevaluation_minorgoal_minorobjective_minorope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='th_id',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
