# Generated by Django 3.2 on 2021-05-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majoractivity',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='majoractivity',
            name='responsible',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
