# Generated by Django 3.2 on 2021-05-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210506_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='minoractivity',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minoractivity',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
