# Generated by Django 3.2 on 2021-05-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20210507_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minoractivity',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='minoractivity',
            name='introduction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='minoractivity',
            name='major_id',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='minoractivity',
            name='ref1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minoractivity',
            name='ref2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minoractivity',
            name='ref3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minoractivity',
            name='responsible',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='minoractivity',
            name='year',
            field=models.IntegerField(default='2564'),
        ),
    ]
