# Generated by Django 3.2 on 2021-05-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20210507_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minoractivity',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='minoractivity',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
