# Generated by Django 3.2 on 2021-05-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20210507_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
