# Generated by Django 3.2 on 2021-05-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_member_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majoractivity',
            options={'ordering': ('id',), 'verbose_name': 'โครงการ', 'verbose_name_plural': 'ข้อมูลโครงการ'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('id',), 'verbose_name': 'สมาชิก', 'verbose_name_plural': 'ข้อมูลสมาชิก'},
        ),
        migrations.AlterModelOptions(
            name='minoractivity',
            options={'ordering': ('id',), 'verbose_name': 'กิจกรรม', 'verbose_name_plural': 'ข้อมูลกิจกรรม'},
        ),
        migrations.AlterModelOptions(
            name='minorbenefit',
            options={'ordering': ('id',), 'verbose_name': 'ผลที่คาดว่าจะได้รับ', 'verbose_name_plural': 'ผลที่คาดว่าจะได้รับ'},
        ),
        migrations.AlterModelOptions(
            name='minorcost',
            options={'ordering': ('id',), 'verbose_name': 'รายการใช้เงิน', 'verbose_name_plural': 'รายการใช้เงิน'},
        ),
        migrations.AlterModelOptions(
            name='minorevaluation',
            options={'ordering': ('id',), 'verbose_name': 'การประเมินผล', 'verbose_name_plural': 'การประเมินผล'},
        ),
        migrations.AlterModelOptions(
            name='minorgoal',
            options={'ordering': ('id',), 'verbose_name': 'เป้าหมาย', 'verbose_name_plural': 'เป้าหมาย'},
        ),
        migrations.AlterModelOptions(
            name='minorobjective',
            options={'ordering': ('id',), 'verbose_name': 'วัตถุประสงค์', 'verbose_name_plural': 'วัตถุประสงค์'},
        ),
        migrations.AlterModelOptions(
            name='minoroperation',
            options={'ordering': ('id',), 'verbose_name': 'การดำเนินการ', 'verbose_name_plural': 'การดำเนินการ'},
        ),
        migrations.AlterField(
            model_name='minoractivity',
            name='introduction',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='minorobjective',
            name='minor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
