# Generated by Django 3.2 on 2021-05-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20210508_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinorIntroduction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minor_id', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('detail', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'หลักการและเหตุผล',
                'verbose_name_plural': 'หลักการและเหตุผล',
                'ordering': ('id',),
            },
        ),
    ]
