# Generated by Django 3.2 on 2021-05-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_minorintroduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='minorcost',
            name='totalmoney',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='minoroperation',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='minoroperation',
            name='detail',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='minoroperation',
            name='responsible',
            field=models.CharField(max_length=100),
        ),
    ]
