# Generated by Django 3.2 on 2021-05-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20210509_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baseschooldata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_dta', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'ข้อมูลหลักโรงเรียน',
                'verbose_name_plural': 'ข้อมูลหลักโรงเรียน',
                'ordering': ('id',),
            },
        ),
    ]
