# Generated by Django 3.2 on 2021-05-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_minoractivity_cutoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usemoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('minor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('type_money', models.CharField(max_length=100)),
                ('money', models.DecimalField(decimal_places=2, max_digits=7)),
                ('detail', models.TextField()),
                ('unit', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
