# Generated by Django 3.2 on 2021-05-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_usemoney_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numberofuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('no', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
