# Generated by Django 3.2 on 2021-05-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_numberofuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberofuse',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
