# Generated by Django 3.2 on 2021-05-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_alter_numberofuse_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberofuse',
            name='minor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
