# Generated by Django 3.2 on 2021-05-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_numberofuse_minor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberofuse',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
