# Generated by Django 3.2 on 2021-05-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_numberofuse_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='usemoney',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
