# Generated by Django 3.2 on 2021-05-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_usemoney_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usemoney',
            name='type_money',
        ),
        migrations.AddField(
            model_name='numberofuse',
            name='type_money',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
