# Generated by Django 3.2 on 2021-05-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_auto_20210528_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberofuse',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
