# Generated by Django 3.2 on 2021-05-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_numberofuse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='minoractivity',
            name='money_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='minoractivity',
            name='money_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='minoractivity',
            name='money_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='numberofuse',
            name='status',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
