# Generated by Django 3.2 on 2021-06-07 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_auto_20210606_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
