# Generated by Django 3.2 on 2021-06-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_member_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='path',
            new_name='image_file',
        ),
    ]
