# Generated by Django 3.2 on 2021-06-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_rename_path_member_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='classroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
