# Generated by Django 3.2 on 2021-06-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkname',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('st_id', models.CharField(max_length=20)),
                ('sem', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studentdata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('st_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('sex', models.CharField(max_length=30)),
                ('th_id', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('b_date', models.DateField(blank=True, null=True)),
                ('classroom', models.IntegerField(blank=True, null=True)),
                ('room', models.IntegerField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'นักเรียน',
                'verbose_name_plural': 'ข้อมูลนักเรียน',
                'ordering': ('id',),
            },
        ),
    ]
