# Generated by Django 3.2 on 2021-06-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='th_id',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
