# Generated by Django 3.2 on 2021-06-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkname',
            name='classroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkname',
            name='room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
